version: '3.8'

name: caiodonalisio-website

services:

  nginx:
    container_name: webserver
    build: ./nginx
    ports:
      - 3334:80
    depends_on:
      - web
    networks:
      - defaultnetwork

  web:
    container_name: website
    build: .
    volumes:
      - ./:/usr/src/
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - defaultnetwork
    links:
      - db:db
    depends_on:
      - db
  
  db:
    container_name: database
    image: postgres:16.4-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - defaultnetwork

volumes:
  postgres_data:

networks:
  defaultnetwork:
    driver: bridge