# Generated by Django 5.1.1 on 2024-10-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.SlugField(unique=True)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='date updated')),
                ('flags', models.JSONField()),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
            ],
        ),
    ]
