# Generated by Django 5.1.1 on 2024-10-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('ready', models.BooleanField(default=True)),
                ('display', models.BooleanField(default=True)),
                ('post_type', models.CharField(default='m', max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('display_name', models.CharField(max_length=200, verbose_name='display name')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('flags', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=60)),
                ('pub_year', models.CharField(blank=True, default='', max_length=10)),
                ('publisher', models.CharField(blank=True, default='', max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
