# Generated by Django 5.1.1 on 2024-10-07 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date updated'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('separator', models.CharField(max_length=20, null=True)),
                ('subtitle', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=60)),
                ('pub_year', models.CharField(max_length=10)),
                ('publisher', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
