# Generated by Django 5.1.1 on 2024-10-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_update_date_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='separator',
        ),
    ]
