# Generated by Django 5.1.1 on 2024-10-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_book_separator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flags',
            field=models.JSONField(default={'display': False, 'ready': True}),
        ),
    ]
