# Generated by Django 5.1.1 on 2024-10-07 23:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flags',
            field=models.JSONField(default=blog.models.default_post_flags),
        ),
    ]
