# Generated by Django 5.1.1 on 2024-10-08 13:57

import django.core.validators
import django.db.models.deletion
import monitor_estante_virtual.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress')], max_length=100)),
                ('total_books_found', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo_ou_autor', models.CharField(blank=True, default='', max_length=100)),
                ('titulo', models.CharField(blank=True, default='', max_length=100)),
                ('autor', models.CharField(blank=True, default='', max_length=100)),
                ('editora', models.CharField(blank=True, default='', max_length=100)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('vendedor', models.CharField(blank=True, default='', max_length=100)),
                ('idioma', models.CharField(blank=True, default='', max_length=100)),
                ('preco_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('preco_max', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('ano_de_publicacao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)])),
                ('tipo_de_livro', models.CharField(choices=[('', ''), ('novo', 'novo'), ('usado', 'usado'), ('ambos', 'ambos')], default='', max_length=100)),
                ('isbn', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flags', models.JSONField(default=monitor_estante_virtual.models.default_user_flags)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('publisher', models.CharField(blank=True, default='', max_length=100)),
                ('publication_year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_type', models.CharField(choices=[('', ''), ('novo', 'novo'), ('usado', 'usado'), ('ambos', 'ambos')], default='', max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=1000, unique=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_estante_virtual.collection')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_estante_virtual.query'),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_estante_virtual.user'),
        ),
    ]
